fix: Github integration cleanup
sizzldev/ctrlplane pull request #20
Opened 2024-09-06 03:11 UTC by adityachoudhari26

2024-09-06 05:28 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubConnectedOrgs.tsx
> +interface GithubConnectedOrgsProps {
use types for props, stop using cursor

2024-09-06 05:28 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/page.tsx
> +  const deleteGithubUser = api.github.user.delete.useMutation();
fix lint error

2024-09-06 05:29 UTC, jsbroks reviewed
fix all the linting issues

2024-09-06 06:12 UTC, adityachoudhari26 commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubAddOrgDialog.tsx
> +                <PopoverContent className="w-[466px] p-0">
had to explicitly set the width here, using `w-full` or `w-max` does not work

2024-09-06 19:30 UTC, zacharyblasczyk requested changes
I think some things can be simplified.

2024-09-06 19:30 UTC, zacharyblasczyk commented on apps/webservice/src/app/api/github/installation/route.ts
> +};
This file is cooked. 

```tsx
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { createAppAuth } from "@octokit/auth-app";
import { Octokit } from "@octokit/rest";
import { BAD_REQUEST, INTERNAL_SERVER_ERROR, NOT_FOUND, UNAUTHORIZED } from "http-status";

import { auth } from "@ctrlplane/auth";
import { eq, takeFirstOrNull } from "@ctrlplane/db";
import { db } from "@ctrlplane/db/client";
import { user, workspace } from "@ctrlplane/db/schema";
import { env } from "~/env";
import { api } from "~/trpc/server";

const createOctokit = (installationId?: number) =>
  env.GITHUB_BOT_APP_ID
    ? new Octokit({
        authStrategy: createAppAuth,
        auth: {
          appId: env.GITHUB_BOT_APP_ID,
          privateKey: env.GITHUB_BOT_PRIVATE_KEY,
          clientId: env.GITHUB_BOT_CLIENT_ID,
          clientSecret: env.GITHUB_BOT_CLIENT_SECRET,
          ...(installationId && { installationId }),
        },
      })
    : null;

const jsonErrorResponse = (message: string, status: number) =>
  NextResponse.json({ error: message }, { status });

export const GET = async (req: NextRequest) => {
  const { searchParams } = new URL(req.url);
  const installationId = searchParams.get("installation_id");
  const setupAction = searchParams.get("setup_action");

  if (!installationId || setupAction !== "install") {
    return jsonErrorResponse("Invalid installation ID or setup action", BAD_REQUEST);
  }

  const session = await auth();
  if (!session) {
    return jsonErrorResponse("Unauthorized", UNAUTHORIZED);
  }

  const userData = await db
    .select()
    .from(user)
    .where(eq(user.id, session.user.id))
    .then(takeFirstOrNull);

  if (!userData?.activeWorkspaceId) {
    return jsonErrorResponse("Workspace not found or unauthorized", NOT_FOUND);
  }

  const activeWorkspace = await db
    .select()
    .from(workspace)
    .where(eq(workspace.id, userData.activeWorkspaceId))
    .then(takeFirstOrNull);

  if (!activeWorkspace) {
    return jsonErrorResponse("Workspace not found", NOT_FOUND);
  }

  const octokit = createOctokit();
  if (!octokit) {
    return jsonErrorResponse("GitHub bot not configured", INTERNAL_SERVER_ERROR);
  }

  const installation = await octokit.apps.getInstallation({
    installation_id: Number(installationId),
    headers: { "X-GitHub-Api-Version": "2022-11-28" },
  });

  if (installation.data.target_type !== "Organization" || !installation.data.account) {
    return jsonErrorResponse("Invalid installation type", BAD_REQUEST);
  }

  const installationOctokit = createOctokit(installation.data.id);
  if (!installationOctokit) {
    return jsonErrorResponse("Failed to get installation octokit", INTERNAL_SERVER_ERROR);
  }

  const orgData = await installationOctokit.orgs.get({
    org: String(installation.data.target_id),
    headers: { "X-GitHub-Api-Version": "2022-11-28" },
  });

  await Promise.all([
    api.github.organizations.create({
      workspaceId: activeWorkspace.id,
      installationId: installation.data.id,
      organizationName: orgData.data.login,
      avatarUrl: orgData.data.avatar_url,
      addedByUserId: userData.id,
    }),
    api.job.agent.create({
      workspaceId: activeWorkspace.id,
      type: "github-app",
      name: orgData.data.login,
      config: {
        installationId: installation.data.id,
        owner: orgData.data.login,
      },
    }),
  ]);

  const baseUrl = await api.runtime.baseUrl();
  return NextResponse.redirect(`${baseUrl}/${activeWorkspace.slug}/settings/workspace/integrations/github`);
};
```

2024-09-06 19:30 UTC, zacharyblasczyk commented on apps/webservice/src/app/api/github/installation/route.ts
> +  );
I don't think you need the baseurl

2024-09-06 19:30 UTC, zacharyblasczyk commented on packages/api/src/router/github/create-github-org.ts
> +  });
Same here:
```tsx
const createOctokitInstance = (installationId?: number) =>
  new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: env.GITHUB_BOT_APP_ID,
      privateKey: env.GITHUB_BOT_PRIVATE_KEY,
      clientId: env.GITHUB_BOT_CLIENT_ID,
      clientSecret: env.GITHUB_BOT_CLIENT_SECRET,
      ...(installationId && { installationId }),
    },
  });
  ```

2024-09-07 04:18 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubAddOrgDialog.tsx
> +  workspaceSlug: string;
is this used?

2024-09-07 04:20 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubConnectedOrgs.tsx
> +  workspaceSlug?: string;
why not just pass in workspace?

workspace: {slug: string, id: string}

2024-09-07 04:20 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubConnectedOrgs.tsx
> +  const githubOrgsInstalled = await api.github.organizations.list(
do you need to do a null check to enable this query?

2024-09-07 04:20 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubAddOrgDialog.tsx
> +    api.github.organizations.list.useQuery(workspaceId);
do you need to do a null check to enable this query?

2024-09-07 04:20 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubAddOrgDialog.tsx
> +    githubUser?.githubUserId ?? 0,
do you need to do a null check to enable this query?

2024-09-07 04:21 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubRemoveOrgDialog.tsx
> +}
use types, and use `&` instead, this is the OOP

2024-09-07 04:26 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/GithubAddOrgDialog.tsx
> +                    className="relative mb-4 flex w-fit flex-col gap-2 rounded-md bg-neutral-800/50 px-4 py-3 text-muted-foreground"
flex row, aling icon at top of row

2024-09-07 04:27 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/OrgActionDropdown.tsx
> +          rel="noopener noreferrer"
lmfao bet you have no idea what cursor is doing here

2024-09-07 04:28 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/page.tsx
> -  const githubBotClientId = api.runtime.github.clientId.useQuery();
can we remove these endpoints

2024-09-07 04:28 UTC, jsbroks commented on apps/webservice/src/app/[workspaceSlug]/settings/(settings)/workspace/integrations/(integration)/github/page.tsx
> +            loading={false}
remove loading...

2024-09-07 04:57 UTC, jsbroks commented on packages/api/src/router/github/create-github-org.ts
> +type ParsedConfigFile = ConfigFile & {
zod supports `z.infer<typeof configFile>`

2024-09-07 04:58 UTC, jsbroks commented on packages/api/src/router/github/create-github-org.ts
> +  return {
1 line

2024-09-07 04:58 UTC, jsbroks commented on packages/api/src/router/github/create-github-org.ts
> +            .map((d) => d.content.deployments.map((d) => d.system))
flatMap

2024-09-07 04:58 UTC, jsbroks commented on packages/api/src/router/github/create-github-org.ts
> +            .map((d) => d.content.deployments.map((d) => d.workspace))
flatMap

2024-09-07 05:00 UTC, jsbroks commented on packages/api/src/router/github/create-github-org.ts
> +    });
1 line, no need for return

be more descriptive, give these vars names for the data they are providing

```suggestion
    ]).then(([valueA, valueB]) => 
      [...valueA.data.items, ...valueBdata.items]
    );
```

2024-09-07 05:00 UTC, jsbroks commented on packages/api/src/router/github/github.ts
> +    .mutation(async ({ ctx, input }) =>
need aysnc here?

2024-09-07 05:01 UTC, jsbroks commented on packages/api/src/router/github/github.ts
> +        .then((data) => data[0]),
```suggestion
        .then(([data]) => data),
```

why do we need this? use takeFirst?

2024-09-21 23:26 UTC, closed without merging